services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
      # - 8080:8080 # Dashboard
    # env_file:
    #   - .env
    # environment:
    #   - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - ./config/traefik.yaml:/etc/traefik/traefik.yaml:ro
      - ./logs:/var/log/traefik
      - letsencrypt:/letsencrypt:rw
    networks:
      - traefik

networks:
  traefik:
    name: traefik
    external: false

volumes:
  letsencrypt:
    name: letsencrypt
    driver: local
