services:
  pocketbase:
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - pocketbase:0.22.23
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./pb_data:/pb/pb_data
