services:
  npm:
    image: "jc21/nginx-proxy-manager:latest"
    container_name: npm
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt
    networks:
      - default

networks:
  default:
    name: npm
    external: false
    driver: bridge

volumes:
  npm_data:
    name: npm_data
    driver: local
  npm_letsencrypt:
    name: npm_letsencrypt
    driver: local
